POM file
sql-machine-learning/zeppelin-sqlflow pull request #21
Opened 2021-06-09 03:28 UTC by Klay1124

fix #16

POM file for the new interpreter project.

2021-06-12 14:45 UTC, weiguoz commented on pom.xml
> +
Remove the empty line.

2021-06-15 02:35 UTC, Klay1124 commented on pom.xml
> +
The empty line has been deleted.

2021-06-15 03:12 UTC, weiguoz requested changes
Please review the file carefully, thanks.

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +								<followSymlinks>false</followSymlinks>
indent?

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +				<!--<plugin>
Why we need these commented lines?

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +
Meaningless blank.

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +								</outputDirectory>
one line?

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +
Meaningless blank.

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +
Meaningless blank.

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +									</exclude>
one line?

2021-06-15 03:12 UTC, weiguoz commented on pom.xml
> +								</exclude>
one line?

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +								<followSymlinks>false</followSymlinks>
It has been corrected.

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +				<!--<plugin>
It has been corrected.

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +
It has been corrected.

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +								</outputDirectory>
It has been corrected.

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +
It has been corrected.

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +
It has been corrected.

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +									</exclude>
It has been corrected.

2021-06-15 07:28 UTC, Klay1124 commented on pom.xml
> +								</exclude>
It has been corrected.

2021-06-16 05:37 UTC, weiguoz approved these changes

2021-06-16 05:37 UTC, merged